Repository friggframework/frigg, pull requests merged in 2024-03, with the labels that each got.

#280 Fix MS Teams refresh token and patch version 0.
  api-module-library/microsoft-teams/api/api.js
Labels: patch

#281 V1 connectwise module
  api-module-library/connectwise/api.js
  api-module-library/connectwise/definition.js
  api-module-library/connectwise/index.js
  api-module-library/connectwise/models/credential.js
  api-module-library/connectwise/models/entity.js
  api-module-library/connectwise/package.json
  api-module-library/connectwise/tests/api.test.js
  api-module-library/connectwise/tests/auther.test.js
Labels: major

#285 release v1 connectwise (again)
  api-module-library/connectwise/api.js
  api-module-library/connectwise/definition.js
  api-module-library/connectwise/index.js
  api-module-library/connectwise/models/credential.js
  api-module-library/connectwise/models/entity.js
  api-module-library/connectwise/package.json
  api-module-library/connectwise/tests/api.test.js
  api-module-library/connectwise/tests/auther.test.js
Labels: major

#288 Small tweak for HubSpot, next and patch test
  api-module-library/hubspot/package.json
Labels: patch, release

#290 slight fix to mock integration module instantiation
  packages/devtools/test-environment/mock-integration.js
Labels: patch

#292 Implement createFile function in google drive
  api-module-library/google-drive/api.js
Labels: patch
