Repository friggframework/frigg, pull requests merged in 2024-08, with the labels that each got.

#322 CLI for Frigg - Install command for now
  package-lock.json
  packages/devtools/frigg-cli/backendJs.js
  packages/devtools/frigg-cli/backendPath.js
  packages/devtools/frigg-cli/commitChanges.js
  packages/devtools/frigg-cli/environmentVariables.js
  packages/devtools/frigg-cli/environmentVariables.test.js
  packages/devtools/frigg-cli/index.js
  packages/devtools/frigg-cli/index.test.js
  packages/devtools/frigg-cli/installCommand.js
  packages/devtools/frigg-cli/installPackage.js
  packages/devtools/frigg-cli/integrationFile.js
  packages/devtools/frigg-cli/logger.js
  packages/devtools/frigg-cli/template.js
  packages/devtools/frigg-cli/validatePackage.js
  packages/devtools/package.json
Labels: minor

#324 Add READMEs that will need updating, but for version releasing
  packages/core/README.md
  packages/devtools/README.md
Labels: release

#326 Fix bug during local running
  packages/core/module-plugin/module-factory.js
Labels: bug, patch, release

#327 Add support for secrets loading from SECRET_ARN
  packages/core/core/create-handler.js
  packages/core/core/secrets-to-env.js
Labels: patch, release

#325 Feat: FRI-224 Start an UI library for common integration use cases
  .github/workflows/frigg-ci.js.yml
  .github/workflows/release.yml
  docs/.gitbook/assets/Frigg Management API.yml
  package-lock.json
  packages/core/integrations/integration-base.js
  packages/devtools/frigg-cli/environmentVariables.test.js
  packages/ui/.eslintrc.cjs
  packages/ui/.gitignore
  packages/ui/README.md
  packages/ui/components.json
  packages/ui/index.html
  packages/ui/jsconfig.json
  packages/ui/lib/App.jsx
  packages/ui/lib/api/api.js
  packages/ui/lib/components/LoadingSpinner.jsx
  packages/ui/lib/components/button.jsx
  packages/ui/lib/components/dialog.jsx
  packages/ui/lib/components/dropdown-menu.jsx
  packages/ui/lib/components/index.js
  packages/ui/lib/components/input.jsx
  packages/ui/lib/components/switch.jsx
  packages/ui/lib/components/table.jsx
  packages/ui/lib/components/toast.jsx
  packages/ui/lib/components/toaster.jsx
  packages/ui/lib/components/use-toast.js
  packages/ui/lib/components/utils.js
  packages/ui/lib/index.css
  packages/ui/lib/index.js
  packages/ui/lib/integration/APISearchDropdownRenderer.jsx
  packages/ui/lib/integration/Data.jsx
  packages/ui/lib/integration/Form.jsx
  packages/ui/lib/integration/IntegrationDropdown.jsx
  packages/ui/lib/integration/IntegrationHorizontal.jsx
  packages/ui/lib/integration/IntegrationList.jsx
  packages/ui/lib/integration/IntegrationSkeleton.jsx
  packages/ui/lib/integration/IntegrationVertical.jsx
  packages/ui/lib/integration/QuickActionsMenu.jsx
  packages/ui/lib/integration/RedirectFromAuth.jsx
  packages/ui/lib/integration/ToggleSwitch.jsx
  packages/ui/lib/integration/customTesterFunction.js
  packages/ui/lib/integration/index.js
  packages/ui/lib/integration/modals/FormBasedAuthModal.jsx
  packages/ui/lib/integration/modals/IntegrationConfigurationModal.jsx
  packages/ui/lib/integration/modals/SampleDataModal.jsx
  packages/ui/lib/integration/modals/UserActionModal.jsx
  packages/ui/lib/integration/modals/index.js
  packages/ui/lib/main.jsx
  packages/ui/lib/utils/IntegrationUtils.js
  packages/ui/lib/utils/logger.js
  packages/ui/package.json
  packages/ui/postcss.config.js
  packages/ui/tailwind.config.js
  packages/ui/vite.config.js
Labels: release
